/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.service.personalcontext.hint;

import static java.util.Objects.requireNonNull;

import android.annotation.FlaggedApi;
import android.annotation.Hide;
import android.annotation.NonNull;
import android.annotation.Nullable;
import android.annotation.SystemApi;
import android.annotation.TestApi;
import android.service.personalcontext.Flags;
import android.service.personalcontext.RenderToken;
import android.service.personalcontext.insight.ContextInsight;

import java.security.GeneralSecurityException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import javax.crypto.spec.SecretKeySpec;

/**
 * Wrapper for a {@link ContextHint} that includes verified information about provenance. Instances
 * will be provided to {@link android.service.personalcontext.refiner.HintRefinerService}, and
 * {@link android.service.personalcontext.understander.ContextUnderstanderService} service
 * implementations. Instances will also be available from {@link ContextInsight#getOriginHints()}.
 *
 * <p>When a {@link ContextHint} is published,
 * {@link com.android.server.personalcontext.PersonalContextManagerService} generates a
 * {@link PublishedContextHint}. Using the contents of the hint to create a byte-level
 * signature,  {@link PublishedContextHint} guarantees that the content has not been manipulated
 * when passed between various PersonalContext components, which only work with
 * {@link PublishedContextHint} instances. The signature is ultimately checked when an
 * {@link ContextInsight} is published with the hint. The insight will not be delivered to the
 * renderers if the signature is invalid.
 */
// TODO(b/516534291): Mark this as deprecated.
@SystemApi
@FlaggedApi(Flags.FLAG_ENABLE_PERSONAL_CONTEXT_SERVICE)
public final class PublishedContextHint {
    @TestApi
    public static final String HMAC_ALGORITHM = "HmacSHA256";

    private final ContextHint mHint;

    @Hide
    public PublishedContextHint(ContextHint hint) {
        mHint = requireNonNull(hint);
    }

    /** Returns the {@link ContextHint} contained in this wrapper. */
    @NonNull
    public ContextHint getContextHint() {
        return mHint;
    }

    /** Returns the {@link PublishedContextHint} hints that were used to create this hint. */
    @NonNull
    public Set<PublishedContextHint> getAttributionHints() {
        final Set<PublishedContextHint> publishedAttributionHints = new HashSet<>();
        for (ContextHint attributionHint : mHint.getAttributionHints()) {
            publishedAttributionHints.add(new PublishedContextHint(attributionHint));
        }
        return publishedAttributionHints;
    }

    /**
     * Returns the package that originated this hint.
     *
     * <p>This value will be "android" if the hint originated from the system instead of from an
     * external component. Code that cares about the origin or correctness of the hint can assume
     * that the hint was generated by the system, and not be some other APK, and that the hint
     * contents have not been tampered with.
     *
     * @return the package that created the hint or null when the originating package is unknown
     */
    @NonNull
    public String getOriginatingPackage() {
        // PublishedContextHint should only be used with published hints. In those cases, this field
        // is guaranteed to be non-null.
        return mHint.getPublishingPackage();
    }

    /** Returns the {@link RenderToken}s that are associated with this hint. */
    @NonNull
    public Set<RenderToken> getRenderTokens() {
        return mHint.getRenderTokens();
    }

    /**
     * Checks that the data hasn't been tampered with.
     */
    @TestApi
    public boolean isSignatureValid(@NonNull SecretKeySpec secretKey)
            throws GeneralSecurityException {
        return true;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        final PublishedContextHint that = (PublishedContextHint) o;
        return Objects.equals(mHint, that.mHint);
    }

    @Override
    public int hashCode() {
        return mHint.hashCode();
    }

    @Override
    public String toString() {
        return "PublishedContextHint{"
                + "contextHint=" + mHint
                + '}';
    }

    /**
     * Utility method to unwrap a collection of {@link PublishedContextHint} into a list of
     * {@link ContextHint}.
     */
    @Hide
    @NonNull
    public static List<ContextHint> unwrapList(
            @NonNull Collection<PublishedContextHint> wrappers) {
        return unwrapInto(wrappers, new ArrayList<>());
    }

    /**
     * Utility method to unwrap a collection of {@link PublishedContextHint} into a collection
     * of {@link ContextHint}.
     */
    @Hide
    @NonNull
    public static <T extends Collection<ContextHint>> T unwrapInto(
            @NonNull Collection<PublishedContextHint> wrappers,
            @NonNull T into) {
        for (PublishedContextHint wrapper : wrappers) {
            into.add(wrapper.getContextHint());
        }
        return into;
    }

    /**
     * Builder for {@link PublishedContextHint}.
     */
    @TestApi
    public static final class Builder {
        private final @NonNull ContextHint mHint;
        private final @NonNull List<PublishedContextHint> mAttributionHints = new ArrayList<>();
        private @Nullable String mOriginatingPackageName = "android";
        private final @Nullable Set<RenderToken> mRenderTokens = new HashSet<>();

        @Hide
        public Builder(
                @NonNull ContextHintWrapper contextHintWrapper, @NonNull SecretKeySpec secretKey) {
            mHint = requireNonNull(contextHintWrapper.getContextHint());
        }

        /** Used by CTS tests to create an instance of {@link PublishedContextHint}. */
        public Builder(@NonNull ContextHint contextHint, @NonNull SecretKeySpec secretKey) {
            this(new ContextHintWrapper(contextHint), secretKey);
        }

        /** Sets the originating package of the ContextHint. */
        @NonNull
        public Builder setOriginatingPackage(@Nullable String originatingPackageName) {
            mOriginatingPackageName = originatingPackageName;
            return this;
        }

        /** Sets the RenderToken. */
        @NonNull
        public Builder addRenderTokens(@NonNull Collection<RenderToken> renderTokens) {
            mRenderTokens.addAll(renderTokens);
            return this;
        }

        /** Adds an attribution hint. */
        @NonNull
        public Builder addAttributionHint(@NonNull PublishedContextHint hint) {
            mAttributionHints.add(hint);
            return this;
        }

        /** Adds multiple attribution hint. */
        @NonNull
        public Builder addAttributionHints(@NonNull Collection<PublishedContextHint> hints) {
            mAttributionHints.addAll(hints);
            return this;
        }

        /** Signs the data pieces and builds an instance of {@link PublishedContextHint}. */
        @NonNull
        public PublishedContextHint build() throws GeneralSecurityException {
            // Build the new instance.
            return new PublishedContextHint(mHint.attachPublisherInfo(
                    mOriginatingPackageName,
                    PublishedContextHint.unwrapList(mAttributionHints),
                    mRenderTokens));
        }
    }
}
