// This file is autogenerated

package android.os.flagging.statslog;


import android.os.Build;
import android.util.StatsEvent;
import android.util.StatsLog;



/**
 * Utility class for logging statistics events.
 */
@android.annotation.Hide
public final class AconfigStatsLog {
    // Constants for atom codes.

    /**
     * AconfigErrorOccurred aconfig_error_occurred<br>
     * Usage: StatsLog.write(StatsLog.ACONFIG_ERROR_OCCURRED, int operation, int error);<br>
     */
    public static final int ACONFIG_ERROR_OCCURRED = 1342;

    // Constants for enum values.

    // Values for AconfigErrorOccurred.operation
    public static final int ACONFIG_ERROR_OCCURRED__OPERATION__ACONFIG_OPERATION_UNSPECIFIED = 0;
    public static final int ACONFIG_ERROR_OCCURRED__OPERATION__ACONFIG_OPERATION_LOAD_PLATFORM_PACKAGE_MAP = 1;
    public static final int ACONFIG_ERROR_OCCURRED__OPERATION__ACONFIG_OPERATION_LOAD_MAINLINE_PACKAGE_MAP = 2;
    public static final int ACONFIG_ERROR_OCCURRED__OPERATION__ACONFIG_OPERATION_OTA_STAGING = 3;

    // Values for AconfigErrorOccurred.error
    public static final int ACONFIG_ERROR_OCCURRED__ERROR__ACONFIG_ERROR_UNSPECIFIED = 0;
    public static final int ACONFIG_ERROR_OCCURRED__ERROR__ACONFIG_ERROR_NONE = 1;

    // Annotation constants.
    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_IS_UID = StatsLog.ANNOTATION_ID_IS_UID;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_TRUNCATE_TIMESTAMP = StatsLog.ANNOTATION_ID_TRUNCATE_TIMESTAMP;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_PRIMARY_FIELD = StatsLog.ANNOTATION_ID_PRIMARY_FIELD;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_EXCLUSIVE_STATE = StatsLog.ANNOTATION_ID_EXCLUSIVE_STATE;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_PRIMARY_FIELD_FIRST_UID = StatsLog.ANNOTATION_ID_PRIMARY_FIELD_FIRST_UID;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_DEFAULT_STATE = StatsLog.ANNOTATION_ID_DEFAULT_STATE;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_TRIGGER_STATE_RESET = StatsLog.ANNOTATION_ID_TRIGGER_STATE_RESET;

    @android.annotation.SuppressLint("InlinedApi")
    public static final byte ANNOTATION_ID_STATE_NESTED = StatsLog.ANNOTATION_ID_STATE_NESTED;


    // Write methods
    public static void write(int code, int arg1, int arg2) {
        final StatsEvent.Builder builder = StatsEvent.newBuilder();
        builder.setAtomId(code);
        builder.writeInt(arg1);
        builder.writeInt(arg2);

        builder.usePooledBuffer();
        StatsLog.write(builder.build());
    }

}
