// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5fwcCG02QLRdggguRdRG9ztKbYyLyDI',
    appId: '1:1048245201646:web:6a339e2fde0c127a8fe1ff',
    messagingSenderId: '1048245201646',
    projectId: 'komun-nebeng-2',
    authDomain: 'komun-nebeng-2.firebaseapp.com',
    storageBucket: 'komun-nebeng-2.firebasestorage.app',
    measurementId: 'G-KD0YD8LZ9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ60_-zYGsZcxlwiN4yRt4rZJW62KYAi4',
    appId: '1:1048245201646:android:3e22c5f03a0294b68fe1ff',
    messagingSenderId: '1048245201646',
    projectId: 'komun-nebeng-2',
    storageBucket: 'komun-nebeng-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDyMAox-H9jGjRIJOhWEE27zYjj4RgbBc',
    appId: '1:1048245201646:ios:0b7806ef77ca3b378fe1ff',
    messagingSenderId: '1048245201646',
    projectId: 'komun-nebeng-2',
    storageBucket: 'komun-nebeng-2.firebasestorage.app',
    iosBundleId: 'com.komun.komunNebeng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDyMAox-H9jGjRIJOhWEE27zYjj4RgbBc',
    appId: '1:1048245201646:ios:0b7806ef77ca3b378fe1ff',
    messagingSenderId: '1048245201646',
    projectId: 'komun-nebeng-2',
    storageBucket: 'komun-nebeng-2.firebasestorage.app',
    iosBundleId: 'com.komun.komunNebeng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5fwcCG02QLRdggguRdRG9ztKbYyLyDI',
    appId: '1:1048245201646:web:decb4b63aed84b528fe1ff',
    messagingSenderId: '1048245201646',
    projectId: 'komun-nebeng-2',
    authDomain: 'komun-nebeng-2.firebaseapp.com',
    storageBucket: 'komun-nebeng-2.firebasestorage.app',
    measurementId: 'G-S8PFDR3PHH',
  );
}
