/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.view;

import android.annotation.Hide;
import android.annotation.NonNull;
import android.annotation.Nullable;
import android.annotation.SuppressLint;
import android.annotation.TestApi;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * Display identifier that is stable across reboots.
 */
// @TestApi without associated feature.
@SuppressLint({"UnflaggedApi", "ParcelNotFinal", "ParcelCreator"})
@TestApi
public abstract class DisplayAddress implements Parcelable {

    @Hide
    public static final int INVALID_PORT = -1;

    @Hide
    public static final int INVALID_DISPLAY_ID = -1;



    /**
     * Creates a StablePhysical DisplayAddress, of type StablePhysical
     * @param physicalDisplayId used to identify the display uniquely.
     * @param port              the connection point of this display
     * @return DisplayAddress
     */
    @Hide
    @NonNull
    public static StablePhysical fromPhysicalDisplayId(long physicalDisplayId, int port) {
        return new StablePhysical(physicalDisplayId, port);
    }



    /**
     * Creates an address for a network display given its MAC address.
     *
     * @param macAddress A MAC address in colon notation.
     * @return The {@link Network} address.
     */
    @Hide
    @NonNull
    public static Network fromMacAddress(String macAddress) {
        return new Network(macAddress);
    }

    /**
     * The port of the display if the display is connected to a physical connector. If the display
     * is not physically connected to the device - e.g. when the display is a Network display -
     * then {@link #INVALID_PORT} is returned.
     * @return The port of the display.
     */
    @Hide
    public int getPort() {
        return INVALID_PORT;
    }

    /**
     * If the display is not physically connected - it will not have a physical display id and
     * therefore {@link #INVALID_DISPLAY_ID} will be returned.
     * @return The physical display id of the display.
     */
    @SuppressLint("UnflaggedApi") // @TestApi without associated feature.
    @TestApi
    public long getPhysicalDisplayId() {
        return INVALID_DISPLAY_ID;
    }

    /**
     * This method compares display addresses from layout config with surface flinger addresses.
     * Ports can be matched, since they are derived from display address or we ensure that the
     * addresses are constructed such that port == physicalDisplayId to match the ports.
     * @param one first display address to compare
     * @param two second display address to compare
     * @return whether the displays are equal.
     */
    @Hide
    public static boolean matchDisplays(DisplayAddress one, DisplayAddress two) {
        if (one instanceof StablePhysical oneStable
                && two instanceof StablePhysical twoStable) {
            if (oneStable.getPhysicalDisplayId() == twoStable.getPhysicalDisplayId()) {
                return true;
            }

            // Only fallback to port matching if at least one address is a "port-only" address
            // generated by DeviceStateToLayoutMap (where physical ID == port).
            boolean isOnePortOnly = oneStable.getPhysicalDisplayId() == (long) oneStable.getPort();
            boolean isTwoPortOnly = twoStable.getPhysicalDisplayId() == (long) twoStable.getPort();

            if (isOnePortOnly || isTwoPortOnly) {
                return oneStable.getPort() == twoStable.getPort();
            }
        }

        return false;
    }

    /**
     * Stable display address for a physically connected display.
     *
     * A {@link StablePhysical} address is represented by a 64-bit identifier from the physical
     * display id. The port, located in the least significant byte, uniquely identifies a physical
     * connector on the device for display output like eDP or HDMI.
     */
    @Hide
    public static final class StablePhysical extends DisplayAddress {
        private final long mPhysicalDisplayId;
        private final int mPort;

        @Override
        public long getPhysicalDisplayId() {
            return mPhysicalDisplayId;
        }

        @Override
        public int getPort() {
            return mPort;
        }

        @Override
        public boolean equals(@Nullable Object other) {
            return other instanceof StablePhysical
                    && mPhysicalDisplayId == ((StablePhysical) other).mPhysicalDisplayId;
        }

        @Override
        public String toString() {
            final StringBuilder builder = new StringBuilder("StablePhysical{")
                    .append("id=").append(mPhysicalDisplayId)
                    .append(", port=").append(getPort());

            return builder.append("}").toString();
        }

        @Override
        public int hashCode() {
            return Long.hashCode(mPhysicalDisplayId);
        }

        @Override
        public void writeToParcel(Parcel out, int flags) {
            out.writeLong(mPhysicalDisplayId);
            out.writeInt(mPort);
        }

        private StablePhysical(long physicalDisplayId, int port) {
            mPhysicalDisplayId = physicalDisplayId;
            mPort = port;
        }

        public static final @NonNull Parcelable.Creator<StablePhysical> CREATOR =
                new Parcelable.Creator<>() {
                    @Override
                    public StablePhysical createFromParcel(Parcel in) {
                        return new StablePhysical(in.readLong(), in.readInt());
                    }

                    @Override
                    public StablePhysical[] newArray(int size) {
                        return new StablePhysical[size];
                    }
                };
    }



    /**
     * Address for a network-connected display.
     */
    @Hide
    public static final class Network extends DisplayAddress {
        private final String mMacAddress;

        @Override
        public boolean equals(@Nullable Object other) {
            return other instanceof Network && mMacAddress.equals(((Network) other).mMacAddress);
        }

        @Override
        public String toString() {
            return mMacAddress;
        }

        @Override
        public int hashCode() {
            return mMacAddress.hashCode();
        }

        @Override
        public void writeToParcel(Parcel out, int flags) {
            out.writeString(mMacAddress);
        }

        private Network(String macAddress) {
            mMacAddress = macAddress;
        }

        public static final @NonNull Parcelable.Creator<Network> CREATOR =
                new Parcelable.Creator<Network>() {
                    @Override
                    public Network createFromParcel(Parcel in) {
                        return new Network(in.readString());
                    }

                    @Override
                    public Network[] newArray(int size) {
                        return new Network[size];
                    }
                };
    }

    @Hide
    @SuppressLint("UnflaggedApi")
    @Override
    public int describeContents() {
        return 0;
    }
}
