/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.service.personalcontext.attribution;

import android.annotation.FlaggedApi;
import android.annotation.Hide;
import android.annotation.NonNull;
import android.annotation.SystemApi;
import android.app.Service;
import android.content.Intent;
import android.os.Handler;
import android.os.HandlerExecutor;
import android.os.IBinder;
import android.os.Looper;
import android.service.personalcontext.Flags;
import android.service.personalcontext.IOpCallback;
import android.service.personalcontext.insight.InsightDisplayDetails;
import android.service.personalcontext.insight.interaction.AttributionDetails;
import android.service.personalcontext.understander.ContextUnderstanderService;
import android.service.personalcontext.util.BinderRequestProcessor;

import androidx.annotation.Nullable;

import java.util.concurrent.Executor;

/**
 * Base attribution handler service responsible for handling and displaying
 * data provenance for insights generated by the {@link ContextUnderstanderService}.
 *
 * <p>Subclasses should be hosted within a secure and trusted process that
 * adheres to section 9.8.6 of the Android Compatibility Definition Document (CDD) and this is
 * achieved by either hosting within the PCC sandbox or a PCC trusted component. Failing PCC
 * compliance checks would render the service implementation ineligible to handle or display
 * {@link AttributionDetails} from the PersonalContextManager service.
 *
 * <p>You must declare the service in the AndroidManifest of the app hosting the service with the
 * {@link android.Manifest.permission#BIND_CONTEXT_COMPONENT_SERVICE} permission, and include an
 * intent filter with the necessary action indicating that it is an
 * {@link AttributionHandlerService} ({@link #SERVICE_INTERFACE}). The application must also have
 * the {@link android.Manifest.permission#PERSONAL_CONTEXT_HANDLE_ATTRIBUTION} permission.
 *
 * <p>For example:
 *
 * <pre class="prettyprint">
 * &lt;uses-permission android:name="BIND_CONTEXT_COMPONENT_SERVICE" /&gt;
 * &lt;uses-permission android:name="PERSONAL_CONTEXT_HANDLE_ATTRIBUTION" /&gt;
 * &lt;service android:name=".MyAttributionHandlerService"&gt;
 *     &lt;intent-filter&gt;
 *         &lt;action
 *             android:name="android.service.personalcontext.attribution.AttributionHandlerService"
 *             /&gt;
 *     &lt;/intent-filter&gt;
 * &lt;/service&gt;
 * </pre>
 *
 * @see "Android 16 CDD Section 9.8.6:
 * https://source.android.com/docs/compatibility/16/android-16-cdd#986_os-level_and_ambient_data"
 */
@SystemApi
@FlaggedApi(Flags.FLAG_ENABLE_PERSONAL_CONTEXT_ATTRIBUTION_SUPPORT)
public abstract class AttributionHandlerService extends Service {

    /**
     * The {@link Intent} that must be declared as handled by the service.
     *
     * <p>To be supported, the service must also require the
     * {@link android.Manifest.permission#BIND_CONTEXT_COMPONENT_SERVICE} permission.
     */
    private static final String SERVICE_INTERFACE =
            "android.service.personalcontext.attribution.AttributionHandlerService";

    /**
     * The base {@link Intent} that can be used to bind to the service instance.
     */
    @Hide
    @Nullable
    public static Intent createBindIntent() {
        return new Intent(SERVICE_INTERFACE);
    }

    @Nullable
    @Override
    public final IBinder onBind(@Nullable Intent intent) {
        return new AttributionHandlerService.Binder(
                this, new HandlerExecutor(new Handler(Looper.getMainLooper())));
    }

    /**
     * Receives and handles attribution details for a given insight.
     *
     * <p>For example:
     *
     * <pre class="prettyprint">
     * &#64;Override
     * public void onHandleInsightAttribution(
     *         &#64;NonNull InsightDisplayDetails insightDisplayDetails,
     *         &#64;NonNull AttributionDetails attributionDetails) {
     *
     *     Intent intent = new Intent(this, AttributionActivity.class);
     *     intent.putExtra(KEY_INSIGHT_DISPLAY, insightDisplayDetails);
     *     intent.putExtra(KEY_ATTRIBUTION_INFO, attributionDetails);
     *     startActivity(intent);
     * }
     * </pre>
     *
     * @param insightDisplayDetails Details of the generated insight to display.
     * @param attributionDetails    Corresponding attribution details for the source insight.
     */
    public abstract void onHandleInsightAttribution(
            @NonNull InsightDisplayDetails insightDisplayDetails,
            @NonNull AttributionDetails attributionDetails);

    private static final class Binder extends IAttributionHandler.Stub {
        private final BinderRequestProcessor<AttributionHandlerService> mRequestProcessor;

        Binder(AttributionHandlerService service, Executor executor) {
            mRequestProcessor = new BinderRequestProcessor.Builder<>(service, executor)
                    .build();
        }

        @Override
        public void handleInsightAttribution(
                InsightDisplayDetails insightDisplayDetails,
                AttributionDetails attributionDetails,
                IOpCallback opCallback) {
            mRequestProcessor.execute(
                    new BinderRequestProcessor.ExecutionParams.Builder<AttributionHandlerService>(
                            opCallback, serviceInstance -> {
                        serviceInstance.onHandleInsightAttribution(
                                insightDisplayDetails, attributionDetails);
                    }).build());
        }

    }
}
